spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          # lower-case-service-id: true

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              # - "8081-bdcaafcceecabdaecfbbcebdabeadeba.project.examly.io/"
              # - "http://8081-bdcaafcceecabdaecfbbcebdabeadeba.project.examly.io/"
              # - "https://8081-bdcaafcceecabdaecfbbcebdabeadeba.project.examly.io"
              # - "https://8081-bdcaafcceecabdaecfbbcebdabeadeba.project.examly.io/"
              - "http://localhost:8085/"
              # - "http://localhost:8081/"
              # - "https://ide-bdcaafcceecabdaecfbbcebdabeadeba.project.examly.io/proxy/8081"
              - "http://localhost:8087/"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
            allowedHeaders: "*"
            allowedCredentials: true

eureka:
  client:
    serviceUrl:
      # defaultZone: https://ide-bdcaafcceecabdaecfbbcebdabeadeba.project.examly.io/proxy/8761/eureka
      register-with-eureka: true
