spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          # lower-case-service-id: true

      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:8083/"
              - "http://localhost:8085/"
              - "http://localhost:8087/"

eureka:
  client:
    serviceUrl:
      defaultZone: https://ide-bdcaafcceecabdaecfbbcebdabeadeba.project.examly.io/proxy/8761/eureka
      register-with-eureka: true
